stages:
  - build

# --- JOB PARA LINUX ---
build_linux:
  stage: build
  image: rabits/qt:6.5-desktop
  script:
    - echo "Compilando en Linux (Docker)..."
    - mkdir build_linux
    - cd build_linux
    - qmake ../DDM.pro
    - make
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# --- JOB PARA WINDOWS ---
build_windows:
  stage: build
  tags:
    - windows  # <--- Este tag es obligatorio para que GitLab busque una PC con Windows
  script:
    - echo "Compilando en Windows (Shell)..."
    # Nota: Asegurarse que qmake y nmake estén en el PATH del Runner de Windows
    - qmake DDM.pro -spec win32-msvc
    - nmake
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"