stages:
  - build
# Forzando actualizacion del pipeline
# --- TAREA PARA TU PC (WINDOWS) ---
# Se activa cuando subís cambios y tu Runner está en "run"
build_windows:
  stage: build
  tags:
    - ddm-test-pc  # El tag que le pusiste a tu Runner en la terminal
  script:
    - echo "Compilando para Windows en la PC de Maria..."
    # 1. Configuramos el entorno para que encuentre qmake (ajusta la versión si bajaste otra)
    - $env:Path += ";C:\Qt\6.5.3\msvc2019_64\bin" 
    # 2. Generamos el Makefile
    - qmake DDM.pro -spec win32-msvc
    # 3. Compilamos (nmake es el comando de Visual Studio)
    - nmake
  artifacts:
    paths:
      - release/DDM.exe  # Para que puedas descargar el programa terminado desde GitLab

# --- TAREA PARA EL SERVIDOR DE LA ARMADA (LINUX) ---
# Esta tarea la va a buscar el runner "infra"
build_linux:
  stage: build
  image: rabits/qt:6.5-desktop
  tags:
    - infra  # Buscamos al servidor de la Armada
  script:
    - echo "Compilando para Linux en el servidor INFRA..."
    - qmake DDM.pro
    - make
  artifacts:
    paths:
      - DDM  # El ejecutable de Linux