variables:
  GIT_CLEAN_FLAGS: -ffdx

stages:
  - build
  - release

#Compilacion en windows, develop
build_windows:
  stage: build
  tags:
    - ddm-test-pc
  only:
    - develop
    - linux-version
    - tags
  script:
    - echo "Compilando versión RELEASE en Windows..."
    - $env:Path = "C:\Qt\6.7.3\mingw_64\bin;C:\Qt\Tools\mingw1120_64\bin;" + $env:Path
    - qmake DDM.pro CONFIG+=release
    - mingw32-make
    - windeployqt release\DDM.exe --compiler-runtime
  artifacts:
    name: "DDM-Windows-v$CI_COMMIT_TAG"
    paths:
      - release/

#Compilacion en linux, linux-version
build_linux:
  stage: build
  image: stateoftheartio/qt6:6.7-gcc-aqt
  tags:
    - ddm-linux-local
  only:
    - develop
    - linux-version
    - tags
  script:
    - echo "Imitando el actions/checkout con ref linux-version..."
    # Forzamos a que descargue siempre la rama de Linux, igual que hacias en GitHub
    - git fetch origin linux-version
    - git checkout linux-version
    
    - echo "Compilando versión RELEASE en Ubuntu..."
    - mkdir -p build_linux
    - cd build_linux
    - qmake ../DDM.pro CONFIG+=release
    - make -j$(nproc)
  artifacts:
    name: "DDM-Linux-v$CI_COMMIT_TAG"
    paths:
      - build_linux/

#Generacion de releases
create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  # Saqué el tag ddm-test-pc para que use los runners compartidos de GitLab con Docker
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creando Release unificada para Windows y Linux..."
  release:
    name: 'DDM Release $CI_COMMIT_TAG'
    description: 'Versión oficial para la ARA. Esta release contiene los binarios optimizados (release) para ambos sistemas operativos.'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'Descargar para Windows'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/download?job=build_windows'
        - name: 'Descargar para Linux'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/download?job=build_linux'