name: Validacion Qt Windows

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Instalar Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.*'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64' # Esto es lo estándar para Windows

    - name: Configurar MSVC (Compilador de Windows)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Ejecutar qmake
      shell: cmd
      run: |
        for /r %%i in (DDM.pro) do qmake "%%i" -spec win32-msvc

    - name: Compilar
      shell: cmd
      run: nmake